tasks:
  - init: >
    pip install cpplint
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON &&
    cmake --build build -t all 
vscode:
  extensions:
    - ms-vscode.cpptools@0.28.3:mjRj37VUK0nY2ZeDXzxOJA==
    - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==