name: Check Code Quality

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cpp Check
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
      - name: Publish Report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' 
          
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: "${{ env.WORKING_DIRECTORY }}/coverage/lcov_head.info"
          lcov-base: "${{ env.WORKING_DIRECTORY }}/coverage/lcov.info"
          github-token: "${{ secrets.SA_GITHUB_TOKEN }}"
          delete-old-comments: true
          filter-changed-files: true
