name: CMake

on: [push, pull_request]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#env:
  ## Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Cpp Check
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
      - name: Publish Report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' 

      - name: Check Code Coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          #project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: cobertura.xml
