name: CMake

on: [push, pull_request]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#env:
  ## Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      #- name: Cpp Check
        #uses: deep5050/cppcheck-action@main
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN}}
          
      #- name: Publish Report    
        #uses: mikeal/publish-to-github-action@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #BRANCH_NAME: 'master' 
          
      - name: format code coverage
        uses: ./.github/actions/cc-test-reporter
        with:
          subcommand: "format-coverage -t lcov ./coverage/lcov.info"
          
      - name: upload code coverage
        uses: ./.github/actions/cc-test-reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          subcommand: "upload-coverage"
