name: CMake

on: [push, pull_request]
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#env:
  ## Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      #- name: Cpp Check
        #uses: deep5050/cppcheck-action@main
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
      #- name: Publish Report    
        #uses: mikeal/publish-to-github-action@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # BRANCH_NAME: 'master' 
         
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: sonar-scanner
             -Dsonar.organization=1corp 
             -Dsonar.projectKey=Claro-Club-Mobile 
             -Dsonar.sources=$GITHUB_WORKSPACE 
             -Dsonar.host.url=${{ secrets.SONAR_URL }} 
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
