name: sorting_non_recursive_merge_sort
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  sorting_non_recursive_merge_sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: mattnotmitt/doxygen-action@master
        with:
          working-directory: '.'
          doxyfile-path: 'sorting/doxy.txt'
      - run: |
          cd sorting
          make test
          make doc
